package models

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

// ---------------------------------------------------------------------------
// EXPENSES — PO header (one row per purchase order)
// RECEIVED CHAR(1): 'F' = draft, 'T' = posted/invoiced
// ---------------------------------------------------------------------------

type Expense struct {
	OrderNo      int64           `db:"ORDERNO"`
	Supplier     sql.NullString  `db:"SUPPLIER"`
	SupplierNo   sql.NullString  `db:"SUPPLIERNO"`
	InvoiceNo    sql.NullString  `db:"INVOICENO"`
	PayMethod    sql.NullString  `db:"PAYMETHOD"`
	PayRef       sql.NullString  `db:"PAYREF"`
	InvDate      sql.NullTime    `db:"INVDATE"`
	DiscountDate sql.NullTime    `db:"DISCOUNTDATE"`
	PurchDate    sql.NullTime    `db:"PURCHDATE"`
	OrderDate    sql.NullTime    `db:"ORDERDATE"`
	DueDate      sql.NullTime    `db:"DUEDATE"`
	Received     FBBoolChar      `db:"RECEIVED"` // 'F'=draft, 'T'=posted
	NettTotal    decimal.Decimal `db:"NETTOTAL"`
	VAT          decimal.Decimal `db:"VAT"`
	Discount     decimal.Decimal `db:"DISCOUNT"`
	Ullages      decimal.Decimal `db:"ULLAGES"`
	GrandTotal   decimal.Decimal `db:"GRANDTOTAL"`
	Category     sql.NullString  `db:"CATEGORY"`
	PlacedOrder  sql.NullString  `db:"PLACEDORDER"` // legacy 'N'/'T'/'F'
}

// ---------------------------------------------------------------------------
// PITEMS — PO line items (the working basket)
// NOTE: POSTED is VARCHAR(11), NOT CHAR(1) — use sql.NullString, not FBBoolChar.
// The legacy app writes 'T' or 'F' into it; VARCHAR(11) is an accidental over-width.
// ---------------------------------------------------------------------------

type PItem struct {
	OrderNo      sql.NullInt64   `db:"ORDERNO"`
	ItemNo       sql.NullInt64   `db:"ITEMNO"`
	MPartNo      sql.NullString  `db:"MPARTNO"`
	Description  sql.NullString  `db:"DESCRIPTION"`
	QTY          decimal.Decimal `db:"QTY"`
	Pack         decimal.Decimal `db:"PACK"`
	PackCost     decimal.Decimal `db:"PACKCOST"`
	EachCost     decimal.Decimal `db:"EACHCOST"`
	Supplier     sql.NullString  `db:"SUPPLIER"`
	Category     sql.NullString  `db:"CATEGORY"`
	CostGroup    sql.NullString  `db:"COSTGROUP"`
	CostCategory sql.NullString  `db:"COSTCATEGORY"`
	OrderDate    sql.NullTime    `db:"ORDERDATE"`
	PurchDate    sql.NullTime    `db:"PURCHDATE"`
	InvDate      sql.NullTime    `db:"INVDATE"`
	Purchases    decimal.Decimal `db:"PURCHASES"`
	Posted       sql.NullString  `db:"POSTED"` // 'T' = archived to PITEMSHIS
	TaxRate      sql.NullInt32   `db:"TAXRATE"`
	Discount     decimal.Decimal `db:"DISCOUNT"`
	Units        decimal.Decimal `db:"UNITS"`
	EachUnit     sql.NullString  `db:"EACHUNIT"`
	PackUnit     sql.NullString  `db:"PACKUNIT"`
	Packaging    sql.NullString  `db:"PACKAGING"`
}

// IsPosted returns true when the line has been archived after posting.
func (p *PItem) IsPosted() bool {
	return p.Posted.Valid && (p.Posted.String == "T" || p.Posted.String == "t")
}

// ---------------------------------------------------------------------------
// CREDITORSLEDGER — mirror of EXPENSES at post time; also holds payment rows.
// PK is ORDERNO. Invoice rows share the ORDERNO from EXPENSES.
// Payment credit rows (if paymethod != NOT PAID) get a NEW GEN_ID(ORDERS_GEN).
// ---------------------------------------------------------------------------

type CreditorEntry struct {
	OrderNo      int64           `db:"ORDERNO"`
	Supplier     sql.NullString  `db:"SUPPLIER"`
	SupplierNo   sql.NullString  `db:"SUPPLIERNO"`
	InvoiceNo    sql.NullString  `db:"INVOICENO"`
	PayMethod    sql.NullString  `db:"PAYMETHOD"`
	PayRef       sql.NullString  `db:"PAYREF"`
	InvDate      sql.NullTime    `db:"INVDATE"`
	DiscountDate sql.NullTime    `db:"DISCOUNTDATE"`
	PurchDate    sql.NullTime    `db:"PURCHDATE"`
	OrderDate    sql.NullTime    `db:"ORDERDATE"`
	DueDate      sql.NullTime    `db:"DUEDATE"`
	Received     FBBoolChar      `db:"RECEIVED"`
	NettTotal    decimal.Decimal `db:"NETTOTAL"`
	VAT          decimal.Decimal `db:"VAT"`
	Discount     decimal.Decimal `db:"DISCOUNT"`
	Ullages      decimal.Decimal `db:"ULLAGES"`
	GrandTotal   decimal.Decimal `db:"GRANDTOTAL"`
	Category     sql.NullString  `db:"CATEGORY"`
	PlacedOrder  sql.NullString  `db:"PLACEDORDER"`
}

// ---------------------------------------------------------------------------
// SUPPLIERS
// PK: ITEMNO (generated by suppliers_gen). SUPPLIERNO is the business key.
// BANKINGDETAILS is a BLOB SUB_TYPE 1 — nakagami delivers it as a string.
// ---------------------------------------------------------------------------

type Supplier struct {
	ItemNo         int64          `db:"ITEMNO"`
	SupplierNo     string         `db:"SUPPLIERNO"`
	SupplierAccNo  sql.NullString `db:"SUPPLIERACCNO"`
	Supplier       sql.NullString `db:"SUPPLIER"`
	Address1       sql.NullString `db:"ADDRESS1"`
	Address2       sql.NullString `db:"ADDRESS2"`
	Address3       sql.NullString `db:"ADDRESS3"`
	Zip            sql.NullString `db:"ZIP"`
	Phone          sql.NullString `db:"PHONE"`
	Contact        sql.NullString `db:"CONTACT"`
	Cell           sql.NullString `db:"CELL"`
	Fax            sql.NullString `db:"FAX"`
	Email          sql.NullString `db:"EMAIL"`
	BankingDetails sql.NullString `db:"BANKINGDETAILS"`
	Purch          sql.NullString `db:"PURCH"`
}

// ---------------------------------------------------------------------------
// DMASTER — inventory master. Only the columns the PO module reads/writes.
// ---------------------------------------------------------------------------

type DmasterItem struct {
	MPartNo      string          `db:"MPARTNO"`
	Description  sql.NullString  `db:"DESCRIPTION"`
	SupplierNo   sql.NullString  `db:"SUPPLIERNO"`
	PackCost     decimal.Decimal `db:"PACKCOST"`
	EachCost     decimal.Decimal `db:"EACHCOST"`
	UnitCost     decimal.Decimal `db:"UNITCOST"`
	Pack         decimal.Decimal `db:"PACK"`
	Units        int64           `db:"UNITS"`
	OnOrder      decimal.Decimal `db:"ONORDER"`
	TaxRate      int             `db:"TAXRATE"`
	CostGroup    sql.NullString  `db:"COSTGROUP"`
	CostCategory sql.NullString  `db:"COSTCATEGORY"`
	PackUnit     sql.NullString  `db:"PACKUNIT"`
	EachUnit     sql.NullString  `db:"EACHUNIT"`
	Packaging    sql.NullString  `db:"PACKAGING"`
	Purchases    decimal.Decimal `db:"PURCHASES"`
	WPurchases   decimal.Decimal `db:"WPURCHASES"`
}
