-- Migration: Create STOCK_MOVEMENTS table for audit trail
-- Purpose: Log all inventory movements (GRV, SALE, etc.) per variant
-- This maintains historical record of which variant was moved and conversion to base units
-- Author: System
-- Date: 2026-03-06

CREATE TABLE STOCK_MOVEMENTS (
    MOVEMENT_ID        BIGINT PRIMARY KEY,
    GROUP_ID           BIGINT NOT NULL,
    VARIANT_ITEMPARTNO BIGINT NOT NULL,
    BASE_ITEMPARTNO    BIGINT NOT NULL,
    MOVEMENT_TYPE      VARCHAR(20) NOT NULL,
    QTY_VARIANT        FLOAT NOT NULL,
    QTY_BASE           FLOAT NOT NULL,
    REFERENCE          VARCHAR(100),
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MOVEMENTS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES INVENTORY_GROUPS(GROUP_ID)
);

CREATE INDEX IDX_MOVEMENTS_GROUP ON STOCK_MOVEMENTS(GROUP_ID);
CREATE INDEX IDX_MOVEMENTS_VARIANT ON STOCK_MOVEMENTS(VARIANT_ITEMPARTNO);
CREATE INDEX IDX_MOVEMENTS_TYPE ON STOCK_MOVEMENTS(MOVEMENT_TYPE);
CREATE INDEX IDX_MOVEMENTS_CREATED ON STOCK_MOVEMENTS(CREATED_AT);
