-- Migration: Extend DMASTER table for product grouping support
-- Purpose: Add fields for grouping items, tracking UOM, and marking sellable variants
-- Author: System
-- Date: 2026-03-06

ALTER TABLE DMASTER ADD GROUP_ID BIGINT;
ALTER TABLE DMASTER ADD UOM VARCHAR(50);
ALTER TABLE DMASTER ADD IS_BASE_VARIANT BOOLEAN DEFAULT FALSE;
ALTER TABLE DMASTER ADD IS_SELLABLE BOOLEAN DEFAULT TRUE;

ALTER TABLE DMASTER ADD CONSTRAINT FK_DMASTER_GROUP 
  FOREIGN KEY (GROUP_ID) REFERENCES INVENTORY_GROUPS(GROUP_ID);

CREATE INDEX IDX_DMASTER_GROUPID ON DMASTER(GROUP_ID);
CREATE INDEX IDX_DMASTER_IS_BASE ON DMASTER(IS_BASE_VARIANT);
CREATE INDEX IDX_DMASTER_IS_SELLABLE ON DMASTER(IS_SELLABLE);
