-- Migration: Add ordering-allowed flag to DMASTER for variant ordering control
-- Date: 2026-03-07

ALTER TABLE DMASTER ADD IS_ORDERING_ALLOWED BOOLEAN DEFAULT TRUE;

CREATE INDEX IDX_DMASTER_IS_ORDERING_ALLOWED ON DMASTER(IS_ORDERING_ALLOWED);
