-- Migration 010: Add missing columns to DMASTER table
-- Generated: 2026-03-08
-- Purpose: Sync production schema with local development database
--
-- Missing columns found in production:
--  1. BULKSELLINGPRICE - Bulk pricing field (causing current errors)
--  2. LINKEDSKU - Linked SKU reference
--  3. SUPPLIERSKU - Supplier SKU reference  
--  4. FRIFOS, SATFOS, SUNFOS, THURSFOS, TUESFOS, WEDFOS - Daily stock tracking

-- Add pricing column (critical - app is failing without this)
ALTER TABLE DMASTER ADD BULKSELLINGPRICE NUMERIC(18,2) DEFAULT 0 NOT NULL;

-- Add SKU tracking columns
ALTER TABLE DMASTER ADD LINKEDSKU VARCHAR(50);
ALTER TABLE DMASTER ADD SUPPLIERSKU VARCHAR(50);

-- Add daily stock columns (legacy compatibility)
ALTER TABLE DMASTER ADD FRIFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;
ALTER TABLE DMASTER ADD SATFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;
ALTER TABLE DMASTER ADD SUNFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;
ALTER TABLE DMASTER ADD THURSFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;
ALTER TABLE DMASTER ADD TUESFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;
ALTER TABLE DMASTER ADD WEDFOS NUMERIC(18,3) DEFAULT 0 NOT NULL;

-- Add indexes for queryable columns
CREATE INDEX IDX_DMASTER_LINKEDSKU ON DMASTER(LINKEDSKU);
CREATE INDEX IDX_DMASTER_SUPPLIERSKU ON DMASTER(SUPPLIERSKU);

COMMIT;
