-- Stage 6.3: PERIOD_FINALIZATIONS table
-- Run this script once against dinem.fdb using isql or a Firebird admin tool.
-- Firebird 3.0 does not support CREATE TABLE IF NOT EXISTS — check before running.
--
-- isql example:
--   isql -user SYSDBA -pass masterkey "localhost:3050/c:/Users/herna/aweh.pos/dinem.fdb" -i period_finalizations.sql

CREATE TABLE PERIOD_FINALIZATIONS (
    ID               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STOCK_SHEET      VARCHAR(50)  NOT NULL,
    PERIOD_DATE      DATE         NOT NULL,
    FINALIZED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    FINALIZED_BY     INTEGER,     -- FK to EMPLOYEE.EMPLOYEENO (soft reference, no FK constraint)
    CONSTRAINT UQ_PERIOD_FINAL UNIQUE (STOCK_SHEET, PERIOD_DATE)
);

-- Generator for PERIOD_FINALIZATIONS.ID
-- (Only needed if you prefer GEN_ID over IDENTITY; kept for consistency with the codebase.)
-- CREATE SEQUENCE PERIOD_FINALIZATION_GEN START WITH 1;

-- Verify:
-- SELECT * FROM PERIOD_FINALIZATIONS ORDER BY FINALIZED_AT DESC ROWS 10;
